config/routes.rb
Rails.application.routes.draw do
  resources :comentarios
  resources :categoria
  resources :articulos
  resources :usuarios
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :usuario
  belongs_to :articulo
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: %i[ show edit update destroy ]

  # GET /comentarios or /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1 or /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios or /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: "Comentario was successfully created." }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1 or /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: "Comentario was successfully updated." }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1 or /comentarios/1.json
  def destroy
    @comentario.destroy!

    respond_to do |format|
      format.html { redirect_to comentarios_path, status: :see_other, notice: "Comentario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comentario_params
      params.require(:comentario).permit(:contenido, :usuario_id, :articulo_id)
    end
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/comentarios/_comentario.html.erb
<div id="<%= dom_id comentario %>">
  <p>
    <strong>Contenido:</strong>
    <%= comentario.contenido %>
  </p>

  <p>
    <strong>Usuario:</strong>
    <%= comentario.usuario_id %>
  </p>

  <p>
    <strong>Articulo:</strong>
    <%= comentario.articulo_id %>
  </p>

</div>

app/views/comentarios/_form.html.erb
<%= form_with(model: comentario) do |form| %>
  <% if comentario.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
        <% comentario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :contenido, style: "display: block" %>
    <%= form.text_area :contenido %>
  </div>

  <div>
    <%= form.label :usuario_id, style: "display: block" %>
    <%= form.text_field :usuario_id %>
  </div>

  <div>
    <%= form.label :articulo_id, style: "display: block" %>
    <%= form.text_field :articulo_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<% content_for :title, "Editing comentario" %>

<h1>Editing comentario</h1>

<%= render "form", comentario: @comentario %>

<br>

<div>
  <%= link_to "Show this comentario", @comentario %> |
  <%= link_to "Back to comentarios", comentarios_path %>
</div>

app/views/comentarios/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Comentarios" %>

<h1>Comentarios</h1>

<div id="comentarios">
  <% @comentarios.each do |comentario| %>
    <%= render comentario %>
    <p>
      <%= link_to "Show this comentario", comentario %>
    </p>
  <% end %>
</div>

<%= link_to "New comentario", new_comentario_path %>

app/views/comentarios/new.html.erb
<% content_for :title, "New comentario" %>

<h1>New comentario</h1>

<%= render "form", comentario: @comentario %>

<br>

<div>
  <%= link_to "Back to comentarios", comentarios_path %>
</div>

app/views/comentarios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comentario %>

<div>
  <%= link_to "Edit this comentario", edit_comentario_path(@comentario) %> |
  <%= link_to "Back to comentarios", comentarios_path %>

  <%= button_to "Destroy this comentario", @comentario, method: :delete %>
</div>