config/routes.rb
Rails.application.routes.draw do
  resources :comentarios
  resources :categoria
  resources :articulos
  resources :usuarios
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/articulo.rb
class Articulo < ApplicationRecord
  belongs_to :usuario
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  before_action :set_articulo, only: %i[ show edit update destroy ]

  # GET /articulos or /articulos.json
  def index
    @articulos = Articulo.all
  end

  # GET /articulos/1 or /articulos/1.json
  def show
  end

  # GET /articulos/new
  def new
    @articulo = Articulo.new
  end

  # GET /articulos/1/edit
  def edit
  end

  # POST /articulos or /articulos.json
  def create
    @articulo = Articulo.new(articulo_params)

    respond_to do |format|
      if @articulo.save
        format.html { redirect_to @articulo, notice: "Articulo was successfully created." }
        format.json { render :show, status: :created, location: @articulo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articulos/1 or /articulos/1.json
  def update
    respond_to do |format|
      if @articulo.update(articulo_params)
        format.html { redirect_to @articulo, notice: "Articulo was successfully updated." }
        format.json { render :show, status: :ok, location: @articulo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articulos/1 or /articulos/1.json
  def destroy
    @articulo.destroy!

    respond_to do |format|
      format.html { redirect_to articulos_path, status: :see_other, notice: "Articulo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_articulo
      @articulo = Articulo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def articulo_params
      params.require(:articulo).permit(:titulo, :contenido, :usuario_id)
    end
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/views/articulos/_articulo.html.erb
<div id="<%= dom_id articulo %>">
  <p>
    <strong>Titulo:</strong>
    <%= articulo.titulo %>
  </p>

  <p>
    <strong>Contenido:</strong>
    <%= articulo.contenido %>
  </p>

  <p>
    <strong>Usuario:</strong>
    <%= articulo.usuario_id %>
  </p>


  
</div>

app/views/articulos/_form.html.erb
<%= form_with(model: articulo) do |form| %>
  <% if articulo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(articulo.errors.count, "error") %> prohibited this articulo from being saved:</h2>

      <ul>
        <% articulo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.label :contenido, style: "display: block" %>
    <%= form.text_area :contenido %>
  </div>

  <div>
    <%= form.label :usuario_id, style: "display: block" %>
    <%= form.text_field :usuario_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articulos/edit.html.erb
<% content_for :title, "Editing articulo" %>

<h1>Editing articulo</h1>

<%= render "form", articulo: @articulo %>

<br>

<div>
  <%= link_to "Show this articulo", @articulo %> |
  <%= link_to "Back to articulos", articulos_path %>
</div>

app/views/articulos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Articulos" %>



<div class="container text-center">
<div id="articulos" class="card text-white bg-primary mb-3" style="max-width: 20rem;">
 

  <div class="card-header"><h1>Articulos</h1></div>
  <div class="card-body bg-light">
   <% @articulos.each do |articulo| %>
    <%= render articulo %>
    <p>
      <%= link_to "Show this articulo", articulo %>
      
    </p>

    
   <% end %>

   <%= link_to "Nuevo Articulo", new_articulo_path %>
  </div>
</div>
</div>

app/views/articulos/new.html.erb
<% content_for :title, "New articulo" %>

<h1>New articulo</h1>

<%= render "form", articulo: @articulo %>

<br>

<div>
  <%= link_to "Back to articulos", articulos_path %>
</div>

app/views/articulos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @articulo %>

<div>
  <%= link_to "Edit this articulo", edit_articulo_path(@articulo) %> |
  <%= link_to "Back to articulos", articulos_path %>

  <%= button_to "Destroy this articulo", @articulo, method: :delete %>
</div>